# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
#rdiscount:
#  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: https://rmanak.github.io/
hosturl: https://rmanak.github.io/
baseurl: https://rmanak.github.io/
title: Arman Akbarian
author: Arman Akbarian
description: Personal website
avatar: profile.jpg
# email: arman2@gmail.com
github: rmanak # username
# facebook: armanphotography
instagram: rmanakb
twitter: aarman
linkedin: armanakbarian
#stackoverflow: username   #e.g: users/2735833/proton1h1
# Comment out if you don't want disqus
# disqus: username
#google_analytics: UA-69391421-1
# work: Aida

#include: ['_pages']
# needed for travis-ci build
exclude: [vendor]
include: ['_pages']
