# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
#rdiscount:
#  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://rmanak.github.io/
hosturl: http://www.akbarian.org/
baseurl: /
title: Arman Akbarian
author: Arman Akbarian
description: Personal website and resume
avatar: profile.jpg
email: arman2@gmail.com
github: rmanak # username
facebook: armanphotography 
instagram: rmanakb
#twitter: username
linkedin: armanakbarian
#stackoverflow: username   #e.g: users/2735833/proton1h1
# Comment out if you don't want disqus 
# disqus: username
#google_analytics: UA-69391421-1

#include: ['_pages']
# needed for travis-ci build
exclude: [vendor]
include: ['_pages']
